language: node_js
node_js:
  - "4"
  - "5"
  - "node"
script:
  - npm run test
  - npm run pree2e && npm run e2e

install:
  - npm install

notifications:
  email: false

branches:
  only:
    - master